/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface AsyncActionCancel
 */
export interface AsyncActionCancel {
    /**
     * The async action's unique identifier.
     * @type {string}
     * @memberof AsyncActionCancel
     */
    action_id?: string;
    /**
     * The type of operation that is running.
     * @type {string}
     * @memberof AsyncActionCancel
     */
    operation_type?: string;
    /**
     * If action cancellation has been scheduled.
     * @type {boolean}
     * @memberof AsyncActionCancel
     */
    scheduled?: boolean;
    /**
     * Cancellation result message.
     * @type {string}
     * @memberof AsyncActionCancel
     */
    message?: string;
}

/**
 * Check if a given object implements the AsyncActionCancel interface.
 */
export function instanceOfAsyncActionCancel(value: object): boolean {
    const isInstance = true;

    return isInstance;
}

export function AsyncActionCancelFromJSON(json: any): AsyncActionCancel {
    return AsyncActionCancelFromJSONTyped(json, false);
}

export function AsyncActionCancelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncActionCancel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action_id': !exists(json, 'action_id') ? undefined : json['action_id'],
        'operation_type': !exists(json, 'operation_type') ? undefined : json['operation_type'],
        'scheduled': !exists(json, 'scheduled') ? undefined : json['scheduled'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function AsyncActionCancelToJSON(value?: AsyncActionCancel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action_id': value.action_id,
        'operation_type': value.operation_type,
        'scheduled': value.scheduled,
        'message': value.message,
    };
}

