/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface AsyncActionStatus
 */
export interface AsyncActionStatus {
    /**
     * The async action's unique identifier.
     * @type {string}
     * @memberof AsyncActionStatus
     */
    action_id?: string;
    /**
     * The status of the action.
     * @type {string}
     * @memberof AsyncActionStatus
     */
    status?: string;
    /**
     * The type of operation that is running.
     * @type {string}
     * @memberof AsyncActionStatus
     */
    operation_type?: string;
    /**
     * An estimated time of when the action may be complete and any output ready to retrieve.
     * @type {Date}
     * @memberof AsyncActionStatus
     */
    estimated_completion?: Date | null;
}

/**
 * Check if a given object implements the AsyncActionStatus interface.
 */
export function instanceOfAsyncActionStatus(value: object): boolean {
    const isInstance = true;

    return isInstance;
}

export function AsyncActionStatusFromJSON(json: any): AsyncActionStatus {
    return AsyncActionStatusFromJSONTyped(json, false);
}

export function AsyncActionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncActionStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action_id': !exists(json, 'action_id') ? undefined : json['action_id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'operation_type': !exists(json, 'operation_type') ? undefined : json['operation_type'],
        'estimated_completion': !exists(json, 'estimated_completion') ? undefined : (json['estimated_completion'] === null ? null : new Date(json['estimated_completion'])),
    };
}

export function AsyncActionStatusToJSON(value?: AsyncActionStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action_id': value.action_id,
        'status': value.status,
        'operation_type': value.operation_type,
        'estimated_completion': value.estimated_completion === undefined ? undefined : (value.estimated_completion === null ? null : value.estimated_completion.toISOString()),
    };
}

