/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EvaluateActionOutput,
    EvaluateActionOutputFromJSONTyped,
    EvaluateActionOutputToJSON,
} from './EvaluateActionOutput';
import {
    FeatureConvictionActionOutput,
    FeatureConvictionActionOutputFromJSONTyped,
    FeatureConvictionActionOutputToJSON,
} from './FeatureConvictionActionOutput';
import {
    GenericActionOutput,
    GenericActionOutputFromJSONTyped,
    GenericActionOutputToJSON,
} from './GenericActionOutput';
import {
    PairwiseDistancesActionOutput,
    PairwiseDistancesActionOutputFromJSONTyped,
    PairwiseDistancesActionOutputToJSON,
} from './PairwiseDistancesActionOutput';
import {
    ReactActionOutput,
    ReactActionOutputFromJSONTyped,
    ReactActionOutputToJSON,
} from './ReactActionOutput';
import {
    ReactAggregateActionOutput,
    ReactAggregateActionOutputFromJSONTyped,
    ReactAggregateActionOutputToJSON,
} from './ReactAggregateActionOutput';
import {
    ReactGroupActionOutput,
    ReactGroupActionOutputFromJSONTyped,
    ReactGroupActionOutputToJSON,
} from './ReactGroupActionOutput';
import {
    ReactIntoFeaturesActionOutput,
    ReactIntoFeaturesActionOutputFromJSONTyped,
    ReactIntoFeaturesActionOutputToJSON,
} from './ReactIntoFeaturesActionOutput';
import {
    ReactSeriesActionOutput,
    ReactSeriesActionOutputFromJSONTyped,
    ReactSeriesActionOutputToJSON,
} from './ReactSeriesActionOutput';
import {
    TrainActionOutput,
    TrainActionOutputFromJSONTyped,
    TrainActionOutputToJSON,
} from './TrainActionOutput';
import {
    TraineeActionOutput,
    TraineeActionOutputFromJSONTyped,
    TraineeActionOutputToJSON,
} from './TraineeActionOutput';

/**
 * @type AsyncActionCompleteOutput
 * The success response object for async action output.
 * @export
 */
export type AsyncActionCompleteOutput = { operation_type: 'acquire_trainee_resources' } & GenericActionOutput | { operation_type: 'analyze' } & GenericActionOutput | { operation_type: 'auto_analyze' } & GenericActionOutput | { operation_type: 'create_trainee' } & TraineeActionOutput | { operation_type: 'evaluate' } & EvaluateActionOutput | { operation_type: 'generic' } & GenericActionOutput | { operation_type: 'get_feature_conviction' } & FeatureConvictionActionOutput | { operation_type: 'impute' } & GenericActionOutput | { operation_type: 'pairwise_distances' } & PairwiseDistancesActionOutput | { operation_type: 'react' } & ReactActionOutput | { operation_type: 'react_aggregate' } & ReactAggregateActionOutput | { operation_type: 'react_group' } & ReactGroupActionOutput | { operation_type: 'react_into_features' } & ReactIntoFeaturesActionOutput | { operation_type: 'react_series' } & ReactSeriesActionOutput | { operation_type: 'train' } & TrainActionOutput;

export function AsyncActionCompleteOutputFromJSON(json: any): AsyncActionCompleteOutput {
    return AsyncActionCompleteOutputFromJSONTyped(json, false);
}

export function AsyncActionCompleteOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncActionCompleteOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['operation_type']) {
        case 'acquire_trainee_resources':
            return {...GenericActionOutputFromJSONTyped(json, true), operation_type: 'acquire_trainee_resources'};
        case 'analyze':
            return {...GenericActionOutputFromJSONTyped(json, true), operation_type: 'analyze'};
        case 'auto_analyze':
            return {...GenericActionOutputFromJSONTyped(json, true), operation_type: 'auto_analyze'};
        case 'create_trainee':
            return {...TraineeActionOutputFromJSONTyped(json, true), operation_type: 'create_trainee'};
        case 'evaluate':
            return {...EvaluateActionOutputFromJSONTyped(json, true), operation_type: 'evaluate'};
        case 'generic':
            return {...GenericActionOutputFromJSONTyped(json, true), operation_type: 'generic'};
        case 'get_feature_conviction':
            return {...FeatureConvictionActionOutputFromJSONTyped(json, true), operation_type: 'get_feature_conviction'};
        case 'impute':
            return {...GenericActionOutputFromJSONTyped(json, true), operation_type: 'impute'};
        case 'pairwise_distances':
            return {...PairwiseDistancesActionOutputFromJSONTyped(json, true), operation_type: 'pairwise_distances'};
        case 'react':
            return {...ReactActionOutputFromJSONTyped(json, true), operation_type: 'react'};
        case 'react_aggregate':
            return {...ReactAggregateActionOutputFromJSONTyped(json, true), operation_type: 'react_aggregate'};
        case 'react_group':
            return {...ReactGroupActionOutputFromJSONTyped(json, true), operation_type: 'react_group'};
        case 'react_into_features':
            return {...ReactIntoFeaturesActionOutputFromJSONTyped(json, true), operation_type: 'react_into_features'};
        case 'react_series':
            return {...ReactSeriesActionOutputFromJSONTyped(json, true), operation_type: 'react_series'};
        case 'train':
            return {...TrainActionOutputFromJSONTyped(json, true), operation_type: 'train'};
        default:
            throw new Error(`No variant of AsyncActionCompleteOutput exists with 'operation_type=${json['operation_type']}'`);
    }
}

export function AsyncActionCompleteOutputToJSON(value?: AsyncActionCompleteOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['operation_type']) {
        case 'acquire_trainee_resources':
            return GenericActionOutputToJSON(value);
        case 'analyze':
            return GenericActionOutputToJSON(value);
        case 'auto_analyze':
            return GenericActionOutputToJSON(value);
        case 'create_trainee':
            return TraineeActionOutputToJSON(value);
        case 'evaluate':
            return EvaluateActionOutputToJSON(value);
        case 'generic':
            return GenericActionOutputToJSON(value);
        case 'get_feature_conviction':
            return FeatureConvictionActionOutputToJSON(value);
        case 'impute':
            return GenericActionOutputToJSON(value);
        case 'pairwise_distances':
            return PairwiseDistancesActionOutputToJSON(value);
        case 'react':
            return ReactActionOutputToJSON(value);
        case 'react_aggregate':
            return ReactAggregateActionOutputToJSON(value);
        case 'react_group':
            return ReactGroupActionOutputToJSON(value);
        case 'react_into_features':
            return ReactIntoFeaturesActionOutputToJSON(value);
        case 'react_series':
            return ReactSeriesActionOutputToJSON(value);
        case 'train':
            return TrainActionOutputToJSON(value);
        default:
            throw new Error(`No variant of AsyncActionCompleteOutput exists with 'operation_type=${value['operation_type']}'`);
    }

}

