/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import type { AsyncActionAcceptedTracking } from './AsyncActionAcceptedTracking';
import {
    AsyncActionAcceptedTrackingFromJSON,
    AsyncActionAcceptedTrackingToJSON,
} from './AsyncActionAcceptedTracking';

/**
 * 
 * @export
 * @interface AsyncActionAccepted
 */
export interface AsyncActionAccepted {
    /**
     * The async action's unique identifier.
     * @type {string}
     * @memberof AsyncActionAccepted
     */
    action_id?: string;
    /**
     * The type of operation that is running.
     * @type {string}
     * @memberof AsyncActionAccepted
     */
    operation_type?: string;
    /**
     * 
     * @type {AsyncActionAcceptedTracking}
     * @memberof AsyncActionAccepted
     */
    tracking?: AsyncActionAcceptedTracking;
    /**
     * An estimated time of when the action may be complete and any output ready to retrieve.
     * @type {Date}
     * @memberof AsyncActionAccepted
     */
    estimated_completion?: Date | null;
    /**
     * A timestamp of when the action will be rejected if it has not yet been acted upon.
     * @type {Date}
     * @memberof AsyncActionAccepted
     */
    rejected_after?: Date | null;
}

/**
 * Check if a given object implements the AsyncActionAccepted interface.
 */
export function instanceOfAsyncActionAccepted(value: object): boolean {
    const isInstance = true;

    return isInstance;
}

export function AsyncActionAcceptedFromJSON(json: any): AsyncActionAccepted {
    return AsyncActionAcceptedFromJSONTyped(json, false);
}

export function AsyncActionAcceptedFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncActionAccepted {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action_id': !exists(json, 'action_id') ? undefined : json['action_id'],
        'operation_type': !exists(json, 'operation_type') ? undefined : json['operation_type'],
        'tracking': !exists(json, 'tracking') ? undefined : AsyncActionAcceptedTrackingFromJSON(json['tracking']),
        'estimated_completion': !exists(json, 'estimated_completion') ? undefined : (json['estimated_completion'] === null ? null : new Date(json['estimated_completion'])),
        'rejected_after': !exists(json, 'rejected_after') ? undefined : (json['rejected_after'] === null ? null : new Date(json['rejected_after'])),
    };
}

export function AsyncActionAcceptedToJSON(value?: AsyncActionAccepted | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action_id': value.action_id,
        'operation_type': value.operation_type,
        'tracking': AsyncActionAcceptedTrackingToJSON(value.tracking),
        'estimated_completion': value.estimated_completion === undefined ? undefined : (value.estimated_completion === null ? null : value.estimated_completion.toISOString()),
        'rejected_after': value.rejected_after === undefined ? undefined : (value.rejected_after === null ? null : value.rejected_after.toISOString()),
    };
}

