/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime";
/**
 * The failure response object for async action output.
 * @export
 * @interface AsyncActionFailedOutput
 */
export interface AsyncActionFailedOutput {
  /**
   * The async action's unique identifier.
   * @type {string}
   * @memberof AsyncActionFailedOutput
   */
  action_id?: string;
  /**
   * The status of the action.
   * @type {string}
   * @memberof AsyncActionFailedOutput
   */
  status: string;
  /**
   * The type of operation that is running.
   * @type {string}
   * @memberof AsyncActionFailedOutput
   */
  operation_type: string;
  /**
   *
   * @type {Error}
   * @memberof AsyncActionFailedOutput
   */
  output?: Error;
}

/**
 * Check if a given object implements the AsyncActionFailedOutput interface.
 */
export function instanceOfAsyncActionFailedOutput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "operation_type" in value;

  return isInstance;
}

export function AsyncActionFailedOutputFromJSON(json: any): AsyncActionFailedOutput {
  return AsyncActionFailedOutputFromJSONTyped(json, false);
}

export function AsyncActionFailedOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncActionFailedOutput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    action_id: !exists(json, "action_id") ? undefined : json["action_id"],
    status: json["status"],
    operation_type: json["operation_type"],
    output: !exists(json, "output") ? undefined : json["output"],
  };
}

export function AsyncActionFailedOutputToJSON(value?: AsyncActionFailedOutput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    action_id: value.action_id,
    status: value.status,
    operation_type: value.operation_type,
    output: value.output,
  };
}
