/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime";
/**
 * The cancelled response object for async action output.
 * @export
 * @interface AsyncActionCancelledOutput
 */
export interface AsyncActionCancelledOutput {
  /**
   * The async action's unique identifier.
   * @type {string}
   * @memberof AsyncActionCancelledOutput
   */
  action_id?: string;
  /**
   * The status of the action.
   * @type {string}
   * @memberof AsyncActionCancelledOutput
   */
  status: string;
  /**
   * The type of operation that is running.
   * @type {string}
   * @memberof AsyncActionCancelledOutput
   */
  operation_type: string;
  /**
   *
   * @type {any}
   * @memberof AsyncActionCancelledOutput
   */
  output?: any | null;
}

/**
 * Check if a given object implements the AsyncActionCancelledOutput interface.
 */
export function instanceOfAsyncActionCancelledOutput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "operation_type" in value;

  return isInstance;
}

export function AsyncActionCancelledOutputFromJSON(json: any): AsyncActionCancelledOutput {
  return AsyncActionCancelledOutputFromJSONTyped(json, false);
}

export function AsyncActionCancelledOutputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AsyncActionCancelledOutput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    action_id: !exists(json, "action_id") ? undefined : json["action_id"],
    status: json["status"],
    operation_type: json["operation_type"],
    output: !exists(json, "output") ? undefined : json["output"],
  };
}

export function AsyncActionCancelledOutputToJSON(value?: AsyncActionCancelledOutput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    action_id: value.action_id,
    status: value.status,
    operation_type: value.operation_type,
    output: value.output,
  };
}
