/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface AsyncAction
 */
export interface AsyncAction {
    /**
     * The action id, required to retrieve the result of an individual async action.
     * @type {string}
     * @memberof AsyncAction
     */
    action_id?: string;
    /**
     * The status of the action.
     * @type {string}
     * @memberof AsyncAction
     */
    status?: string;
    /**
     * The type of operation that is running.
     * @type {string}
     * @memberof AsyncAction
     */
    operation_type?: string;
    /**
     * When the action was started in UTC.
     * @type {Date}
     * @memberof AsyncAction
     */
    start_date?: Date;
    /**
     * When the action finished in UTC.
     * @type {Date}
     * @memberof AsyncAction
     */
    end_date?: Date | null;
}

/**
 * Check if a given object implements the AsyncAction interface.
 */
export function instanceOfAsyncAction(value: object): boolean {
    const isInstance = true;

    return isInstance;
}

export function AsyncActionFromJSON(json: any): AsyncAction {
    return AsyncActionFromJSONTyped(json, false);
}

export function AsyncActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action_id': !exists(json, 'action_id') ? undefined : json['action_id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'operation_type': !exists(json, 'operation_type') ? undefined : json['operation_type'],
        'start_date': !exists(json, 'start_date') ? undefined : (new Date(json['start_date'])),
        'end_date': !exists(json, 'end_date') ? undefined : (json['end_date'] === null ? null : new Date(json['end_date'])),
    };
}

export function AsyncActionToJSON(value?: AsyncAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action_id': value.action_id,
        'status': value.status,
        'operation_type': value.operation_type,
        'start_date': value.start_date === undefined ? undefined : (value.start_date.toISOString()),
        'end_date': value.end_date === undefined ? undefined : (value.end_date === null ? null : value.end_date.toISOString()),
    };
}

