/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * The base class for async action output responses.
 * @export
 * @interface BaseAsyncActionOutput
 */
export interface BaseAsyncActionOutput {
    /**
     * The async action's unique identifier.
     * @type {string}
     * @memberof BaseAsyncActionOutput
     */
    action_id?: string;
    /**
     * The status of the action.
     * @type {string}
     * @memberof BaseAsyncActionOutput
     */
    status: string;
    /**
     * The type of operation that is running.
     * @type {string}
     * @memberof BaseAsyncActionOutput
     */
    operation_type: string;
}

/**
 * Check if a given object implements the BaseAsyncActionOutput interface.
 */
export function instanceOfBaseAsyncActionOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "operation_type" in value;

    return isInstance;
}

export function BaseAsyncActionOutputFromJSON(json: any): BaseAsyncActionOutput {
    return BaseAsyncActionOutputFromJSONTyped(json, false);
}

export function BaseAsyncActionOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseAsyncActionOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action_id': !exists(json, 'action_id') ? undefined : json['action_id'],
        'status': json['status'],
        'operation_type': json['operation_type'],
    };
}

export function BaseAsyncActionOutputToJSON(value?: BaseAsyncActionOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action_id': value.action_id,
        'status': value.status,
        'operation_type': value.operation_type,
    };
}

