/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import type { TraineeResources } from './TraineeResources';
import {
    TraineeResourcesFromJSON,
    TraineeResourcesToJSON,
} from './TraineeResources';

/**
 * 
 * @export
 * @interface CopyTraineeRequest
 */
export interface CopyTraineeRequest {
    /**
     * The name of the copy to be created. If not defined the original trainee name is used.
     * @type {string}
     * @memberof CopyTraineeRequest
     */
    new_trainee_name?: string;
    /**
     * The id of the project to create the new trainee in. If not defined, uses user's default project.
     * @type {string}
     * @memberof CopyTraineeRequest
     */
    project_id?: string;
    /**
     * The library type of the new Trainee.
     * "st": use single-threaded library.
     * "mt": use multi-threaded library.
     * @type {string}
     * @memberof CopyTraineeRequest
     */
    library_type?: CopyTraineeRequestLibraryTypeEnum;
    /**
     * 
     * @type {TraineeResources}
     * @memberof CopyTraineeRequest
     */
    resources?: TraineeResources;
}

/**
* @export
* @enum {string}
*/
export type CopyTraineeRequestLibraryTypeEnum = 'st' | 'mt';


/**
 * Check if a given object implements the CopyTraineeRequest interface.
 */
export function instanceOfCopyTraineeRequest(value: object): boolean {
    const isInstance = true;

    return isInstance;
}

export function CopyTraineeRequestFromJSON(json: any): CopyTraineeRequest {
    return CopyTraineeRequestFromJSONTyped(json, false);
}

export function CopyTraineeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopyTraineeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'new_trainee_name': !exists(json, 'new_trainee_name') ? undefined : json['new_trainee_name'],
        'project_id': !exists(json, 'project_id') ? undefined : json['project_id'],
        'library_type': !exists(json, 'library_type') ? undefined : json['library_type'],
        'resources': !exists(json, 'resources') ? undefined : TraineeResourcesFromJSON(json['resources']),
    };
}

export function CopyTraineeRequestToJSON(value?: CopyTraineeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'new_trainee_name': value.new_trainee_name,
        'project_id': value.project_id,
        'library_type': value.library_type,
        'resources': TraineeResourcesToJSON(value.resources),
    };
}

