/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * The requested memory to provision for a compute instance.
 * @export
 * @interface MemoryLimits
 */
export interface MemoryLimits {
    /**
     * The minimum amount of memory to provision (in mebibytes). The compute instance will be guaranteed to receive at
     * least this amount of memory. If the system does not have enough memory resources available the instance will
     * fail to be provisioned.
     * @type {number}
     * @memberof MemoryLimits
     */
    minimum?: number;
    /**
     * The maximum amount of memory to provision (in mebibytes). The compute instance will be allowed to scale to use
     * memory up to this limit if available.  Upon exceeding this limit the compute instance will use swap and may
     * exit with Out-of-memory errors.
     * @type {number}
     * @memberof MemoryLimits
     */
    maximum?: number;
}

/**
 * Check if a given object implements the MemoryLimits interface.
 */
export function instanceOfMemoryLimits(value: object): boolean {
    const isInstance = true;

    return isInstance;
}

export function MemoryLimitsFromJSON(json: any): MemoryLimits {
    return MemoryLimitsFromJSONTyped(json, false);
}

export function MemoryLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryLimits {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'minimum': !exists(json, 'minimum') ? undefined : json['minimum'],
        'maximum': !exists(json, 'maximum') ? undefined : json['maximum'],
    };
}

export function MemoryLimitsToJSON(value?: MemoryLimits | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'minimum': value.minimum,
        'maximum': value.maximum,
    };
}

