/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectIdentity
 */
export interface ProjectIdentity {
    /**
     * The project UUID.
     * @type {string}
     * @memberof ProjectIdentity
     */
    id?: string;
    /**
     * The project name.
     * @type {string}
     * @memberof ProjectIdentity
     */
    name?: string;
}

/**
 * Check if a given object implements the ProjectIdentity interface.
 */
export function instanceOfProjectIdentity(value: object): boolean {
    const isInstance = true;

    return isInstance;
}

export function ProjectIdentityFromJSON(json: any): ProjectIdentity {
    return ProjectIdentityFromJSONTyped(json, false);
}

export function ProjectIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectIdentity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function ProjectIdentityToJSON(value?: ProjectIdentity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

