/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface TraineeAcquireResourcesRequest
 */
export interface TraineeAcquireResourcesRequest {
    /**
     * The maximum seconds to wait to acquire resources.
     * @type {number}
     * @memberof TraineeAcquireResourcesRequest
     */
    timeout?: number;
}

/**
 * Check if a given object implements the TraineeAcquireResourcesRequest interface.
 */
export function instanceOfTraineeAcquireResourcesRequest(value: object): boolean {
    const isInstance = true;

    return isInstance;
}

export function TraineeAcquireResourcesRequestFromJSON(json: any): TraineeAcquireResourcesRequest {
    return TraineeAcquireResourcesRequestFromJSONTyped(json, false);
}

export function TraineeAcquireResourcesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraineeAcquireResourcesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeout': !exists(json, 'timeout') ? undefined : json['timeout'],
    };
}

export function TraineeAcquireResourcesRequestToJSON(value?: TraineeAcquireResourcesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeout': value.timeout,
    };
}

