/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API. 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import type { TraineeRequest } from './TraineeRequest';
import {
    TraineeRequestFromJSON,
    TraineeRequestToJSON,
} from './TraineeRequest';
import type { TraineeResources } from './TraineeResources';
import {
    TraineeResourcesFromJSON,
    TraineeResourcesToJSON,
} from './TraineeResources';

/**
 * 
 * @export
 * @interface TraineeCreateRequest
 */
export interface TraineeCreateRequest {
    /**
     * The library type of the Trainee.
     * "st": use single-threaded library.
     * "mt": use multi-threaded library.
     * @type {string}
     * @memberof TraineeCreateRequest
     */
    library_type?: TraineeCreateRequestLibraryTypeEnum;
    /**
     * The maximum seconds to wait for a trainee to be created.
     * @type {number}
     * @memberof TraineeCreateRequest
     */
    timeout?: number;
    /**
     * 
     * @type {TraineeResources}
     * @memberof TraineeCreateRequest
     */
    resources?: TraineeResources;
    /**
     * 
     * @type {TraineeRequest}
     * @memberof TraineeCreateRequest
     */
    trainee: TraineeRequest;
}

/**
* @export
* @enum {string}
*/
export type TraineeCreateRequestLibraryTypeEnum = 'st' | 'mt';


/**
 * Check if a given object implements the TraineeCreateRequest interface.
 */
export function instanceOfTraineeCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "trainee" in value;

    return isInstance;
}

export function TraineeCreateRequestFromJSON(json: any): TraineeCreateRequest {
    return TraineeCreateRequestFromJSONTyped(json, false);
}

export function TraineeCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraineeCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'library_type': !exists(json, 'library_type') ? undefined : json['library_type'],
        'timeout': !exists(json, 'timeout') ? undefined : json['timeout'],
        'resources': !exists(json, 'resources') ? undefined : TraineeResourcesFromJSON(json['resources']),
        'trainee': TraineeRequestFromJSON(json['trainee']),
    };
}

export function TraineeCreateRequestToJSON(value?: TraineeCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'library_type': value.library_type,
        'timeout': value.timeout,
        'resources': TraineeResourcesToJSON(value.resources),
        'trainee': TraineeRequestToJSON(value.trainee),
    };
}

