/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime";
import type { AccountIdentity } from "./AccountIdentity";
import { AccountIdentityFromJSON, AccountIdentityToJSON } from "./AccountIdentity";
import type { ProjectIdentity } from "./ProjectIdentity";
import { ProjectIdentityFromJSON, ProjectIdentityToJSON } from "./ProjectIdentity";

/**
 *
 * @export
 * @interface TraineeIdentity
 */
export interface TraineeIdentity {
  /**
   * The trainee UUID.
   * @type {string}
   * @memberof TraineeIdentity
   */
  id?: string;
  /**
   * The trainee name.
   * @type {string}
   * @memberof TraineeIdentity
   */
  name?: string;
  /**
   *
   * @type {ProjectIdentity}
   * @memberof TraineeIdentity
   */
  project?: ProjectIdentity;
  /**
   *
   * @type {AccountIdentity}
   * @memberof TraineeIdentity
   */
  created_by?: AccountIdentity;
}

/**
 * Check if a given object implements the TraineeIdentity interface.
 */
export function instanceOfTraineeIdentity(value: object): boolean {
  const isInstance = true;

  return isInstance;
}

export function TraineeIdentityFromJSON(json: any): TraineeIdentity {
  return TraineeIdentityFromJSONTyped(json, false);
}

export function TraineeIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraineeIdentity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
    project: !exists(json, "project") ? undefined : ProjectIdentityFromJSON(json["project"]),
    created_by: !exists(json, "created_by") ? undefined : AccountIdentityFromJSON(json["created_by"]),
  };
}

export function TraineeIdentityToJSON(value?: TraineeIdentity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    project: ProjectIdentityToJSON(value.project),
    created_by: AccountIdentityToJSON(value.created_by),
  };
}
