/**
 * Howso API
 * OpenAPI implementation for interacting with the Howso API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  AnalyzeRequest,
  AppendToSeriesStoreRequest,
  AutoAblationParams,
  EvaluateRequest,
  ImputeRequest,
  ReactAggregateRequest,
  ReactGroupRequest,
  ReactIntoFeaturesRequest,
  ReactRequest,
  ReactSeriesRequest,
  ReduceDataParams,
  RemoveSeriesStoreRequest,
  SetAutoAnalyzeParamsRequest,
  TrainRequest,
  TraineeWorkflowAttributes,
  TraineeWorkflowAttributesRequest,
} from "../models";

export interface AnalyzeOperationRequest {
  trainee_id: string;
  AnalyzeRequest: AnalyzeRequest;
}

export interface AppendToSeriesStoreOperationRequest {
  trainee_id: string;
  AppendToSeriesStoreRequest: AppendToSeriesStoreRequest;
}

export interface AutoAnalyzeRequest {
  trainee_id: string;
}

export interface EvaluateOperationRequest {
  trainee_id: string;
  EvaluateRequest: EvaluateRequest;
}

export interface GetAutoAblationParamsRequest {
  trainee_id: string;
}

export interface GetWorkflowAttributesRequest {
  trainee_id: string;
  TraineeWorkflowAttributesRequest: TraineeWorkflowAttributesRequest;
}

export interface ImputeOperationRequest {
  trainee_id: string;
  ImputeRequest?: ImputeRequest;
}

export interface ReactOperationRequest {
  trainee_id: string;
  ReactRequest: ReactRequest;
}

export interface ReactAggregateOperationRequest {
  trainee_id: string;
  ReactAggregateRequest: ReactAggregateRequest;
}

export interface ReactGroupOperationRequest {
  trainee_id: string;
  ReactGroupRequest: ReactGroupRequest;
}

export interface ReactIntoFeaturesOperationRequest {
  trainee_id: string;
  ReactIntoFeaturesRequest: ReactIntoFeaturesRequest;
}

export interface ReactSeriesOperationRequest {
  trainee_id: string;
  ReactSeriesRequest: ReactSeriesRequest;
}

export interface ReduceDataRequest {
  trainee_id: string;
  ReduceDataParams: ReduceDataParams;
}

export interface RemoveSeriesStoreOperationRequest {
  trainee_id: string;
  RemoveSeriesStoreRequest: RemoveSeriesStoreRequest;
}

export interface SetAutoAblationParamsRequest {
  trainee_id: string;
  AutoAblationParams: AutoAblationParams;
}

export interface SetAutoAnalyzeParamsOperationRequest {
  trainee_id: string;
  SetAutoAnalyzeParamsRequest: SetAutoAnalyzeParamsRequest;
}

export interface SetWorkflowAttributesRequest {
  trainee_id: string;
  TraineeWorkflowAttributes: TraineeWorkflowAttributes;
}

export interface TrainOperationRequest {
  trainee_id: string;
  TrainRequest?: TrainRequest;
}
